### ISSUE TITLE
Vite build fails when library has React code in a ".ts" file

### ISSUE THREAD

**Issue by milang** [vitejs/vite-plugin-react#13] opened 2022-08-13 23:52 UTC
### Describe the bug

Vite build for our application started failing after upgrading `@vitejs/plugin-react` from `2.0.0` to `2.0.1`.

I was able to reproduce this error in the repository https://github.com/milang/vite-issues, branch `plugin-react-201`. It contains `acme-app` generated using `create-vite@3.0.2`, and a simple `acme-lib` that represents our internal library that is causing the build to fail. Reproduction steps:

```shell
git clone https://github.com/milang/vite-issues.git
cd vite-issues
git checkout plugin-react-v201
pnpm install
pnpm run -C packages/acme-app build
# => fails with
# [vite:react-babel] C:\Users\milang\dev\vite-issues\packages\acme-lib\src\styled.ts: Support for the experimental syntax 'flow' isn't currently enabled (3:8):
# ...
```

**Actual behaviour**: Build fails
**Expected behaviour**: Build succeeds

<img width="1092" alt="vite-build-failure" src="https://user-images.githubusercontent.com/42297/184516762-d078fdd6-c288-4f80-8af9-767239ab07a9.png">

### Note 1

A follow-up branch `plugin-react-v200` reverts `@vitejs/plugin-react` back to `2.0.0`. Switching to this branch makes the build succeed:

```shell
# (same directory as above)
git checkout plugin-react-v200 # switch to branch with @vitejs/plugin-react@2.0.0
pnpm install
pnpm run -C packages/acme-app build
# => build succeeds
```

### Note 2

As I was experimenting with the reproduction steps, I noticed that I can simply rename `styled.ts` to `styled.tsx` (changing the file extension), after which the build succeed. While this is a simple "fix", behaviour of version `2.0.0` was IMO much better because it worked without a rename (and rename might not be possible when dealing with a 3rd party library).

```shell
# (same directory as above)
git checkout plugin-react-v201 # switch back to branch with @vitejs/plugin-react@2.0.1
pnpm install
mv packages/acme-lib/src/styled.ts packages/acme-lib/src/styled.tsx # change extension of the problematic file
pnpm run -C packages/acme-app build
# => build succeeds
```

<img width="421" alt="vite-build-success-after-rename" src="https://user-images.githubusercontent.com/42297/184516958-c6b4d35b-5bb4-4e0d-925f-a3c9d5f61a55.png">

### Reproduction

https://github.com/milang/vite-issues/tree/plugin-react-v201

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Memory: 22.11 GB / 31.94 GB
Binaries:
  Node: 16.16.0
  npm: 8.11.0
  pnpm: 7.9.0
Browsers:
  (Not relevant)
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by caghand** [comment] 2022-12-03 09:34
This was also reported here: https://github.com/vitejs/vite/pull/6202#issuecomment-1282127741
As discussed there, the next version of plugin-react won't have this problem anymore.

**Comment by sapphi-red** [comment] 2022-12-19 07:23
Closing as I confirmed the reproduction now works with plugin-react 3.0.0.
I guess this is because `restoreJSX` was removed by https://github.com/vitejs/vite/pull/9590.

**Closed as completed by sapphi-red** 2022-12-19 07:23 UTC
