### ISSUE TITLE
Import in monorepo with babel macro not does not apply 

### ISSUE THREAD

**Issue by Crisis2010** [vitejs/vite-plugin-react#113] opened 2023-02-27 13:43 UTC
### Describe the bug

Trying to import styled-component created by twin.macro, which used babel macro, inside `app` from `lib`.

Seems like problem only when trying import such component from folder, different from root vite app project.

In Reproduction example 
```js
import { Test } from "./../../../libs/utils/src";
```
will get error only in the browser
<img width="1372" alt="CleanShot 2023-02-27 at 16 14 30@2x" src="https://user-images.githubusercontent.com/24792724/221573153-7c9c27ee-3b92-4939-a33a-3ba3d18b4340.png">
Change import from relative style to`@workspace/utils` monorepo way doesn't help, exactly same result

If place same file with `Test` component inside project and change import to
```js
import { Test } from "./utils";
```
Everything works as expected.

Seems like that because when vite try import all scripts without processing them, which cause error

Also if try to build the project, it sucessfully build, but also not work in preview and size of bundle increased 3x times

This is `build` output when import is 
```js
import { Test } from "./../../../libs/utils/src";
```
<img width="467" alt="CleanShot 2023-02-27 at 16 28 40@2x" src="https://user-images.githubusercontent.com/24792724/221576200-f2fb569b-9408-43ea-950c-f1216015d5cd.png">

This is `build` output when import is 
```js
import { Test } from "./utils";
```
<img width="427" alt="CleanShot 2023-02-27 at 16 30 05@2x" src="https://user-images.githubusercontent.com/24792724/221576401-e2d2be4d-df2c-4dda-8786-c56cb350dab8.png">

Seems like babel not applied

Any ideas, maybe im doing something wrong?
Initially, I had this problem when using nx workspace, but after some trying search same issues inside both repositories, it became clear that the problem was precisely how Vite import components from other local projects

Maybe it has something to do with the tasks vitejs/vite#5668 vitejs/vite#7094

### Reproduction

https://github.com/Crisis2010/twin-vite-monorepo-example

### Steps to reproduce

1. npm i
2. npm run dev:dashboard
3. Open localhost
4. Open Console

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 19.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.volta/tools/image/node/18.14.2/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/npm/9.5.1/bin/npm
  Browsers:
    Safari: 16.3
```

### Used Package Manager

npm

### Logs

<details>
<summary>Click to expand!</summary>

```shell

  vite:config bundled config file loaded in 319.02ms +0ms
  vite:esbuild init tsconfck (root: /Users/toothless/Development/Projects/npm-workspaces) +0ms
  vite:esbuild init tsconfck (root: /Users/toothless/Development/Projects/npm-workspaces) +0ms
  vite:esbuild init tsconfck (root: /Users/toothless/Development/Projects/npm-workspaces) +1ms
  vite:esbuild init tsconfck (root: /Users/toothless/Development/Projects/npm-workspaces) +0ms
  vite:esbuild init tsconfck end +3ms
  vite:esbuild init tsconfck end +0ms
  vite:esbuild init tsconfck end +0ms
  vite:esbuild init tsconfck end +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:build-metadata',
  vite:config     'vite:pre-alias',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'vite:react-jsx',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm-helper',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'vite:wasm-fallback',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'vite:force-systemjs-wrap-complete',
  vite:config     'vite:watch-package-data',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'vite:dynamic-import-vars',
  vite:config     'vite:import-glob',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:terser',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback'
  vite:config   ],
  vite:config   optimizeDeps: {
  vite:config     disabled: 'build',
  vite:config     force: undefined,
  vite:config     include: [ 'react/jsx-runtime', 'react/jsx-dev-runtime', 'react' ],
  vite:config     esbuildOptions: { preserveSymlinks: false }
  vite:config   },
  vite:config   build: {
  vite:config     target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {},
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     copyPublicDir: true,
  vite:config     manifest: false,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     ssrEmitAssets: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] },
  vite:config     modulePreload: { polyfill: true }
  vite:config   },
  vite:config   esbuild: {
  vite:config     jsxDev: false,
  vite:config     jsx: 'automatic',
  vite:config     jsxImportSource: undefined,
  vite:config     jsxSideEffects: false
  vite:config   },
  vite:config   resolve: {
  vite:config     mainFields: [ 'module', 'jsnext:main', 'jsnext' ],
  vite:config     browserField: true,
  vite:config     conditions: [],
  vite:config     extensions: [
  vite:config       '.mjs',  '.js',
  vite:config       '.mts',  '.ts',
  vite:config       '.jsx',  '.tsx',
  vite:config       '.json'
  vite:config     ],
  vite:config     dedupe: [ 'react', 'react-dom' ],
  vite:config     preserveSymlinks: false,
  vite:config     alias: [ [Object], [Object] ]
  vite:config   },
  vite:config   configFile: '/Users/toothless/Development/Projects/npm-workspaces/apps/dashboard/vite.config.ts',
  vite:config   configFileDependencies: [
  vite:config     '/Users/toothless/Development/Projects/npm-workspaces/apps/dashboard/vite.config.ts'
  vite:config   ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     optimizeDeps: { force: undefined },
  vite:config     build: {}
  vite:config   },
  vite:config   root: '/Users/toothless/Development/Projects/npm-workspaces/apps/dashboard',
  vite:config   base: '/',
  vite:config   rawBase: '/',
  vite:config   publicDir: '/Users/toothless/Development/Projects/npm-workspaces/apps/dashboard/public',
  vite:config   cacheDir: '/Users/toothless/Development/Projects/npm-workspaces/apps/dashboard/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   ssr: {
  vite:config     format: 'esm',
  vite:config     target: 'node',
  vite:config     optimizeDeps: { disabled: true, esbuildOptions: [Object] }
  vite:config   },
  vite:config   isWorker: false,
  vite:config   mainConfig: null,
  vite:config   isProduction: true,
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     middlewareMode: false,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) { set: [Function (anonymous)] },
  vite:config   createResolver: [Function: createResolver],
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       'vite:build-metadata',
  vite:config       'vite:pre-alias',
  vite:config       'alias',
  vite:config       'vite:modulepreload-polyfill',
  vite:config       'vite:resolve',
  vite:config       'vite:html-inline-proxy',
  vite:config       'vite:css',
  vite:config       'vite:esbuild',
  vite:config       'vite:json',
  vite:config       'vite:wasm-helper',
  vite:config       'vite:worker',
  vite:config       'vite:asset',
  vite:config       'vite:wasm-fallback',
  vite:config       'vite:define',
  vite:config       'vite:css-post',
  vite:config       'vite:build-html',
  vite:config       'vite:worker-import-meta-url',
  vite:config       'vite:asset-import-meta-url',
  vite:config       'vite:force-systemjs-wrap-complete',
  vite:config       'vite:watch-package-data',
  vite:config       'commonjs',
  vite:config       'vite:data-uri',
  vite:config       'vite:dynamic-import-vars',
  vite:config       'vite:import-glob',
  vite:config       'vite:build-import-analysis',
  vite:config       'vite:esbuild-transpile',
  vite:config       'vite:terser',
  vite:config       'vite:load-fallback'
  vite:config     ],
  vite:config     rollupOptions: {},
  vite:config     getSortedPlugins: [Function: getSortedPlugins],
  vite:config     getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config   },
  vite:config   appType: 'spa',
  vite:config   experimental: { importGlobRestoreExtension: false, hmrPartialAccept: false },
  vite:config   getSortedPlugins: [Function: getSortedPlugins],
  vite:config   getSortedPluginHooks: [Function: getSortedPluginHooks]
  vite:config } +12ms
vite v4.1.4 building for production...
✓ 784 modules transformed.
dist/index.html                       0.47 kB
dist/assets/favicon-17e50649.svg      1.52 kB
dist/assets/logo-ecc203fb.svg         2.67 kB
dist/assets/index-2eff615b.css        0.77 kB │ gzip:   0.49 kB
dist/assets/index-89d5797c.js     1,249.78 kB │ gzip: 345.80 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
```
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to [vuejs/core](https://github.com/vuejs/core) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-02-28 12:58
It seems plugin-react does not apply babel plugins to non-project files.
https://github.com/vitejs/vite-plugin-react/blob/45fbe2235fc73c498a952aa3cb2bcacb0a57461a/packages/plugin-react/src/index.ts#L233

**Comment by ArnaudBarre** [comment] 2023-02-28 13:01
Yes I want to get rid of this condition in the the next major. See the end of the second point in: https://github.com/vitejs/vite-plugin-react/pull/53

**Comment by sapphi-red** [comment] 2023-02-28 13:02
Ah, I see. I'll close this as a duplicate of #16.

**Closed as not planned by sapphi-red** 2023-02-28 13:02 UTC
Labels: duplicate
