### ISSUE TITLE
Cannot Polyfill node core modules using vite 4.0.4

### ISSUE THREAD

**Issue by Terkea** [vitejs/vite-plugin-react#95] opened 2023-01-26 20:27 UTC
### Describe the bug

I just started a new react project, I intend to use multiple node modules which require polyfills.
For some reason, I do not seem able to polyfill those. 
I have been trying multiple variations of what I could find over the github/stackoverflow to get this working and I couldn't. 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rm3gjc?file=vite.config.ts

### Steps to reproduce

try to install `jsonwebtoken` in a react app generated using vite 4.0.4 and use the jwt library. It will always crash saying that it couldn't find the util library, process or buffer.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^3.0.1 => 3.0.1 
    vite: ^4.0.4 => 4.0.4
```

### Used Package Manager

npm

### Logs

✘ [ERROR] The injected path "/Users/marian/code/OzoneV2/app-web/node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js" cannot be marked as external

✘ [ERROR] The injected path "/Users/marian/code/OzoneV2/app-web/node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js" cannot be marked as external

Build failed with 2 errors:
error: The injected path "/Users/marian/code/OzoneV2/app-web/node_modules/@esbuild-plugins/node-globals-polyfill/_buffer.js" cannot be marked as external
error: The injected path "/Users/marian/code/OzoneV2/app-web/node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js" cannot be marked as external

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitejs/vite-plugin-react/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitejs/vite-plugin-react/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitejs.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitejs/vite-plugin-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Vite issue and not a framework-specific issue.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite-plugin-react/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment] 2023-01-28 08:24
There's three problems with your reproduction.

1. To alias `import { Buffer } from 'buffer'`, you need to use `buffer: 'vite-compatible-readable-buffer',` instead of `Buffer: 'vite-compatible-readable-buffer',`.
2. `vite-compatible-readable-buffer` package is not installed
3. `vite-compatible-readable-buffer` package does not exist

Closing as this is not a bug in plugin-react nor Vite.

**Closed as completed by sapphi-red** 2023-01-28 08:24 UTC
Labels: invalid
